# querier-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      automountServiceAccountToken: false
      containers:
        - name: thanos-query
          image: quay.io/thanos/thanos:v0.23.0
          imagePullPolicy: Always
          args:
            - query
            - --log.level=debug
            - --query.auto-downsampling
            - --query.replica-label=prometheus_replica
            - --store=dnssrv+_grpc._tcp.prometheus-server.monitoring.svc
            - --store=dnssrv+_grpc._tcp.thanos-store.monitoring.svc
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --query.partial-response
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '200m'
              memory: '256Mi'
          livenessProbe:
              httpGet:
                port: 10902
                path: /-/healthy
          readinessProbe:
            httpGet:
              port: 10902
              path: /-/ready
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
            - name: cluster
              containerPort: 10900
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  labels:
    app: thanos-query
    release: prometheus-operator
    jobLabel: thanos
  namespace: monitoring
spec:
  selector:
    app: thanos-query
  ports:
    - port: 10902
      protocol: TCP
      targetPort: http
      name: http-query
---
