apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator: # This generates prometheus configMap from prometheus.yml
  - name: prometheus-server-conf
    namespace: monitoring
    files:
    - prometheus.yml
labels:
  - pairs:
      name: prometheus-server-conf
