---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s # detect drift and undo kubectl edits every 10mins
  path: ./flux-init/base
  prune: true # remove stale resources from cluster
  sourceRef:
    kind: GitRepository
    name: asb-repo-flux
