---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-log-config
  namespace: fluentbit
data:
  zone: az-westus2-pre
  region: westus2
  lodeLog: loderunner
  ngsaLog: ngsa
  istioLog: ingress
