##################################################################################################
# Details service
##################################################################################################
kind: Namespace
apiVersion: v1
metadata:
  name: burstservice
---
apiVersion: v1
kind: Service
metadata:
  name: burst
  namespace: burstservice
  labels:
    app: burst
    service: burst
spec:
  ports:
  - port: 8080 
    name: http
    nodePort: 30081
  type: NodePort # For external access (k3d, kind)
  selector:
    app: burst
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: burst
  namespace: burstservice
  labels:
    account: burst
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: burst-role
  namespace: burstservice
rules:
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - list
    - get
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - list
    - get
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - list
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: burstservice
  name: burst-rolebind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: burst-role
subjects:
- kind: ServiceAccount
  name: burst
  namespace: burstservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burst
  namespace: burstservice
  labels:
    app: burst
    version: v1
  annotations:
    checkov.io/skip1: CKV_K8S_8=Burst service only supports metrics endpoints
    checkov.io/skip2: CKV_K8S_9=Burst service only supports metrics endpoints
    checkov.io/skip3: CKV_K8S_38=Service account token needs to be mounted to gather HPA metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burst
      version: v1
  template:
    metadata:
      labels:
        app: burst
        version: v1
    spec:
      serviceAccountName: burst
      containers:
      - name: burst
        image: ghcr.io/retaildevcrews/burst-metrics-service:beta
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsUser: 10001
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
          - mountPath: /tmp
            name: tmp
      volumes:
        - emptyDir: {}
          name: tmp
      securityContext:
        seccompProfile:
          type: RuntimeDefault
