replicas: 1

image:
  repository: ghcr.io/retaildevcrews/ngsa-lr
  tag: beta
  pullPolicy: Always

namespace: loderunner

port: 8080

resources:
  limits:
    cpu: "1000m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

service:
  type: ClusterIP
