apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ngsa
spec:
  generators:
  - git:
      repoURL: https://github.com/retaildevcrews/ngsa-asb
      revision: anguyen/argo-spike
      directories:
      - path: spikes/argo-cd/deploy/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/retaildevcrews/ngsa-asb
        targetRevision: anguyen/argo-spike
        path: '{{path}}'
      destination:
        server: ''{{cluster.address}}''
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true