apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ngsa
spec:
  generators:
  - list:
      elements:
      - cluster: argo-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/retaildevcrews/ngsa-asb
        targetRevision: HEAD
        path: spikes/argo-cd/deploy/argo-cluster
      destination: 
        server: https://kubernetes.default.svc
        namespace: ngsa
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
