apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngsa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/retaildevcrews/ngsa-asb
    targetRevision: anguyen/argo-spike
    path: spikes/argo-cd/deploy/ngsa1
  destination: 
    server: https://kubernetes.default.svc
    namespace: ngsa
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
