---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: fluentbit
  labels:
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/name: fluentbit
  annotations:
    checkov.io/skip1: CKV_K8S_35=fluentbit needs secrets as env variables
    checkov.io/skip2: CKV_K8S_20=fluentbit needs to run as root
    checkov.io/skip3: CKV_K8S_22=fluentbit needs to write to fs
    checkov.io/skip4: CKV_K8S_23=fluentbit needs to run as root
    checkov.io/skip5: CKV_K8S_40=fluentbit needs to run as root
    checkov.io/skip6: CKV_K8S_38=fluentbit needs automounted service account token
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentbit
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fluentbit
        app.kubernetes.io/name: fluentbit
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: fluentbit
      terminationGracePeriodSeconds: 10
      containers:
        - name: fluentbit
          image: $ASB_ACR_NAME.azurecr.io/fluent/fluent-bit:1.9.5
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          env:
            - name: WORKSPACE_ID
              valueFrom:
                secretKeyRef:
                  name: fluentbit-secrets
                  key: WorkspaceId
            - name: SHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: fluentbit-secrets
                  key: SharedKey
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: fluentbit-log-config
                  key: region
            - name: ZONE
              valueFrom:
                configMapKeyRef:
                  name: fluentbit-log-config
                  key: zone
            - name: NGSA_LOG
              valueFrom:
                configMapKeyRef:
                  name: fluentbit-log-config
                  key: ngsaLog
            - name: ISTIO_LOG
              valueFrom:
                configMapKeyRef:
                  name: fluentbit-log-config
                  key: istioLog
            - name: LODE_LOG
              valueFrom:
                configMapKeyRef:
                  name: fluentbit-log-config
                  key: lodeLog
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
          securityContext:
            capabilities:
              drop:
                - ALL
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluentbit
