---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-log-config
  namespace: fluentbit
data:
  zone: az-${ASB_SPOKE_LOCATION}-${ASB_ENV}
  region: ${ASB_SPOKE_LOCATION}
  lodeLog: loderunner
  ngsaLog: ngsa
  istioLog: ingress
