apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- 01-namespace.yaml - including namespace in kustomization file because kustomization is in the namespace
- 02-config.yaml
- 03-config-log.yaml
- 04-role.yaml
- 05-daemonset.yaml
