@startuml ClusterAPI-Lifecycle-Hook-Extension

actor user
box "kubernetes cluster"
  participant "Cluster API" as capi
  participant "Lifecycle hook extension deployment" as hook
end box

user -> capi: kubectl apply cluster CRDs to trigger flow
capi -> hook: POST /hooks.runtime.cluster.x-k8s.io/v1alpha1/beforeclustercreate/{name}
activate hook
hook -> hook: perform required actions before cluster is created
hook --> capi
deactivate hook
capi -> capi: create cluster
capi -> hook: POST /hooks.runtime.cluster.x-k8s.io/v1alpha1/aftercontrolplaneinitialized/{name}
activate hook
hook -> hook: perform required actions when control plane is ready
hook --> capi
deactivate hook

@enduml
