apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
- ../../base/apps/monitoring/ # Then apply rest of monitoring
- grafana/04-grafana-pod-identity.yaml
patches:
- path: prometheus/prometheus-patch.yaml
- path: grafana/dashboards/ngsa-az-blocked-traffic.yaml
- path: grafana/dashboards/ngsa-az-monitor-perf.yaml
- path: grafana/dashboards/ngsa-az-monitor-rel.yaml
- path: grafana/grafana-patch.yaml
