apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
  - patch: |
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value: "acraks3i2qzkkxofr7c.azurecr.io/fluxcd/helm-controller:v0.22.2"        
    target:
      kind: Deployment
      name: helm-controller
      namespace: flux-system
  - patch: |
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value: "acraks3i2qzkkxofr7c.azurecr.io/fluxcd/kustomize-controller:v0.27.0"        
    target:
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
  - patch: |
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value: "acraks3i2qzkkxofr7c.azurecr.io/fluxcd/notification-controller:v0.25.1"        
    target:
      kind: Deployment
      name: notification-controller
      namespace: flux-system
  - patch: |
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value: "acraks3i2qzkkxofr7c.azurecr.io/fluxcd/source-controller:v0.26.1"        
    target:
      kind: Deployment
      name: source-controller
      namespace: flux-system
  - patch: |- # Remove default secret volm
      - op: replace
        path: /spec/path
        value: ./flux-init/init-dev
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1beta2
      kind: Kustomization
      name: flux-system
      namespace: flux-system

