apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - values:
                    component: guestbook
                    branchOrTag: pragmatical/cluster-add-ons
                    namespace: addons
                # - values:
                #     component: namespaces
                #     branchOrTag: pragmatical/cluster-add-ons
                #     namespace: argocd
                # - values:
                #     component: helm-guestbook
                #     branchOrTag: pragmatical/cluster-add-ons
                #     namespace: addons
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                # matchExpressions:
                # #   - key: 'addon-{{values.component}}'
                # #     operator: In
                # #     values:
                # #     - "true"
                #   - key: provider
                #     operator: In
                #     values:
                #     - "azure"
                # #   - key: clusterType
                # #     operator: NotIn
                # #     values:
                # #     - "self-managed"
  template:
    metadata:
      name: '{{values.component}}-{{name}}-wrapper'
      labels:
       component: '{{values.component}}'
      #  component-version: '{{values.branchOrTag}}'
       cluster-id: '{{name}}'
       provider: '{{metadata.labels.provider}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/retaildevcrews/ngsa-asb.git
          targetRevision: '{{values.branchOrTag}}'
          ref: values
        - repoURL: https://github.com/retaildevcrews/ngsa-asb.git
          targetRevision: '{{values.branchOrTag}}'
          path: spikes/cluster-add-ons/add-ons/{{values.component}}/deploy
          helm:
            parameters:
            - name: 'spec.destination.server'
              value: '{{server}}'
            - name: 'clusterName'
              value: '{{name}}'
            valueFiles:
            - $values/spikes/cluster-add-ons/clusters/{{name}}/values.yaml

      destination:
        name: 'in-cluster'
        namespace: 'argocd'
      syncPolicy:
        automated:
           prune: false
           selfHeal: true
        retry:
          limit: 3
        syncOptions:      
        - CreateNamespace=true
