apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-special
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
            matchLabels:
              cluster-type: special
  template:
    metadata:
      name: '{{name}}-guestbook-{{metadata.labels.cluster-type}}' # 'name' field of the Secret
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{server}}' # 'server' field of the secret
        namespace: guestbook
