apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ngsa
spec:
  generators:
  - clusters: {}
  # Selector may be used to narrow scope of targeted clusters (Eg. label, cluster secret, etc.)
  # - clusters:
  #     selector:
  #       matchLabels:
  #         labeltest: second
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/retaildevcrews/ngsa-asb
        targetRevision: HEAD
        path: spikes/argo-cd/deploy/argo-cluster
      destination:
        server: '{{server}}'
        # server: '{{server}}-{{metadata.labels.labeltest}}'
        namespace: ngsa
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
          