apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ngsa
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/retaildevcrews/ngsa-asb
        targetRevision: anguyen/argo-spike
        path: spikes/argo-cd/deploy/argo-cluster
      destination:
        server: '{{server}}'
        namespace: ngsa
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true