apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
  - ../../base/apps/istio

patches:
  - patch: |
        - op: replace
          path: "/spec/servers/0/hosts"
          value:
          - "ngsa/ngsa-memory-eastus-pre.austinrdc.dev"
          - "ngsa/ngsa-cosmos-eastus-pre.austinrdc.dev"
          - "ngsa/ngsa-java-eastus-pre.austinrdc.dev"
          - "monitoring/grafana-eastus-pre.austinrdc.dev"
          - "monitoring/thanos-grpc-eastus-pre.austinrdc.dev"
          - "monitoring/thanos-store-grpc-eastus-pre.austinrdc.dev"

        - op: add
          path: "/spec/servers/0/tls"
          value:
            mode: SIMPLE
            serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
            privateKey: /etc/istio/ingressgateway-certs/tls.key
    target:
      kind: Gateway
      name: istio-gateway
      namespace: istio-system

  - patch: |
        - op: replace
          path: "/spec/components/ingressGateways/0/k8s/resources/limits/cpu"
          value: 200m

        - op: replace
          path: "/spec/components/ingressGateways/0/k8s/resources/requests/cpu"
          value: 50m

        - op: replace
          path: "/spec/components/ingressGateways/0/k8s/resources/requests/memory"
          value: 128M

        - op: replace
          path: "/spec/components/ingressGateways/0/k8s/service/loadBalancerIP"
          value: 10.240.4.4
    target:
      kind: IstioOperator
      name: istio-default
      namespace: istio-system

  - patch: |
        - op: replace
          path: "/spec/resourceID"
          value: "/subscriptions/5dc45b2f-bf13-4281-b763-a53f57290aa3/resourceGroups/rg-wcnp-pre/providers/Microsoft.ManagedIdentity/userAssignedIdentities/podmi-ingress-controller"

        - op: replace
          path: "/spec/clientID"
          value: "84bed9de-aaf5-4763-a3e4-ac569f1dc791"
    target:
      kind: AzureIdentity
      name: istio-ingress-id
      namespace: istio-system

  - patch: |
        - op: replace
          path: "/spec/parameters/keyvaultName"
          value: "kv-aks-ri3aov7twb4uy"
    target:
      kind: SecretProviderClass
      name: istio-ingress-tls-secret-csi-akv
      namespace: istio-system
