apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/apps/monitoring/thanos/ # First apply thanos
- ../../base/apps/monitoring/ # Then apply rest of monitoring
patchesStrategicMerge:
  - "thanos/thanos-patch.yaml"
  - "prometheus/prometheus-patch.yaml"
