apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: ngsa-asb-ngsa-id
  namespace: ngsa
spec:
  type: 0
  resourceID: /subscriptions/648dcb5a-de1e-48b2-af6b-fe6ef28d355c/resourcegroups/rg-ngsa-asb-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ngsa-asb-ngsa-id
  clientID: ed1c4c70-e050-48c6-b864-ea1f8695054e

---

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: ngsa-asb-ngsa-id-binding
  namespace: ngsa
spec:
  azureIdentity: ngsa-asb-ngsa-id
  selector: ngsa-asb-ngsa-id

---

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ngsa-secrets
  namespace: ngsa
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "kv-aks-jxdthrti3j3qu"
    objects: |
      array:
        - |
          objectName: CosmosDatabase
          objectType: secret
        - |
          objectName: CosmosCollection
          objectType: secret
        - |
          objectName: CosmosKey
          objectType: secret
        - |
          objectName: CosmosUrl
          objectType: secret
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"
