---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ngsa
  namespace: ngsa
spec:
  dependsOn:
  - name: flux-system
    namespace: flux-system
  - name: istio
    namespace: istio-system
  interval: 1m0s # detect drift and undo kubectl edits every minute
  prune: true # remove stale resources from cluster
  targetNamespace: ngsa # overwrite the ns for resources in path
  path: ./deploy/dev-ngsa-asb-eastus/ngsa
  sourceRef:
    kind: GitRepository
    name: asb-repo-flux
    namespace: flux-system # points to namespace where this GitRepository is
