apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/apps/monitoring/thanos/
patches:
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraks3i2qzkkxofr7c.azurecr.io/thanos/thanos:v0.23.0"        
      target:
        group: apps
        version: v1
        kind: StatefulSet
        name: thanos-compactor
        namespace: monitoring
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraks3i2qzkkxofr7c.azurecr.io/thanos/thanos:v0.23.0"        
      target:
        group: apps
        version: v1
        kind: StatefulSet
        name: thanos-store
        namespace: monitoring 
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraks3i2qzkkxofr7c.azurecr.io/thanos/thanos:v0.23.0"        
      target:
        group: apps
        version: v1
        kind: Deployment
        name: thanos-query
        namespace: monitoring
