apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
              "id": 1,
              "orgId": 1,
              "name": "Azure Monitor",
              "type": "grafana-azure-monitor-datasource",
              "typeLogoUrl": "public/app/plugins/datasource/grafana-azure-monitor-datasource/img/logo.jpg",
              "access": "proxy",
              "url": "/api/datasources/proxy/1",
              "basicAuth": false,
              "isDefault": true,
              "jsonData": {
                  "azureLogAnalyticsSameAs": true,
                  "clientId": "$ASB_GRAFANA_SP_CLIENT_ID",
                  "cloudName": "azuremonitor",
                  "logAnalyticsClientId": "$ASB_GRAFANA_SP_CLIENT_ID",
                  "logAnalyticsDefaultWorkspace": "$ASB_LA_WORKSPACE_ID",
                  "logAnalyticsTenantId": "$ASB_TENANT_ID",
                  "subscriptionId": "$ASB_SUBSCRIPTION_ID",
                  "tenantId": "$ASB_TENANT_ID"
              },
              "secureJsonData": {
                "clientSecret": $AZURE_MONITOR_CLIENT_SECRET
              },
              "editable": true
            },
            {
              "id": 2,
              "orgId": 1,
              "name": "Prometheus",
              "access":"proxy",
              "editable": true,   
              "type": "prometheus",
              "url": "http://prometheus-server.monitoring.svc:9090"
            }
        ]
    }
