---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-bootstrap
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-system
    namespace: flux-system
  interval: 1m0s # detect drift and undo kubectl edits every minute
  prune: true # remove stale resources from cluster
  path: ./deploy/bootstrap-dev # This is where the cluster kustomization.yaml resides for bootstraping application for dev environment
  sourceRef:
    kind: GitRepository
    name: asb-repo-flux
    namespace: flux-system # points to namespace where this GitRepository is
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-eastus
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-system
    namespace: flux-system
  - name: bootstrapped-istio
    namespace: istio-operator
  interval: 1m0s # detect drift and undo kubectl edits every minute
  prune: true # remove stale resources from cluster
  path: ./deploy/dev-ngsa-asb-eastus/flux-kustomization # This is where the cluster kustomization.yaml resides
  sourceRef:
    kind: GitRepository
    name: asb-repo-flux
    namespace: flux-system # points to namespace where this GitRepository is
