apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini:  |
    [auth]
    disable_login_form = true

    [auth.basic]
    enabled = false

    [auth.azuread]
    name = Azure AD
    enabled = true
    allow_sign_up = true
    client_id = 2db12ba8-2378-4792-adbf-a2d1b05c7407
    scopes = openid email profile
    auth_url = https://login.microsoftonline.com/16b3c013-d300-468d-ac64-7eda0820b6d3/oauth2/v2.0/authorize
    token_url = https://login.microsoftonline.com/16b3c013-d300-468d-ac64-7eda0820b6d3/oauth2/v2.0/token
