---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
              "id": 1,
              "orgId": 1,
              "name": "Azure Monitor",
              "type": "grafana-azure-monitor-datasource",
              "typeLogoUrl": "public/app/plugins/datasource/grafana-azure-monitor-datasource/img/logo.jpg",
              "access": "proxy",
              "url": "/api/datasources/proxy/1",
              "basicAuth": false,
              "isDefault": true,
              "jsonData": {
                  "azureLogAnalyticsSameAs": true,
                  "clientId": "d26fa2ad-c0c1-42ce-8989-6a8c5d207e06",
                  "cloudName": "azuremonitor",
                  "logAnalyticsClientId": "d26fa2ad-c0c1-42ce-8989-6a8c5d207e06",
                  "logAnalyticsDefaultWorkspace": "${AZURE_LA_WORKSPACE}",
                  "logAnalyticsTenantId": "16b3c013-d300-468d-ac64-7eda0820b6d3",
                  "subscriptionId": "5dc45b2f-bf13-4281-b763-a53f57290aa3",
                  "tenantId": "16b3c013-d300-468d-ac64-7eda0820b6d3"
              },
              "secureJsonData": {
                "clientSecret": "$AZURE_MONITOR_CLIENT_SECRET"
              },
              "editable": true
            },
            {
              "id": 2,
              "orgId": 1,
              "name": "Prometheus",
              "access":"proxy",
              "editable": true,
              "type": "prometheus",
              "url": "${PROMETHEUS_QUERY_URL}"
            }
        ]
    }
