apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-prometheus
  namespace: {{.Values.namespace}}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: {{.Values.spec.destination.namespace}}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    chart: {{ .Values.source.chart }}
    helm:
      parameters:
      - name: 'configmapReload.prometheus.enabled'
        value: '{{ .Values.configmapReload.prometheus.enabled}}'
  syncPolicy:
    automated:
        prune: false
        selfHeal: true
    retry:
      limit: 3
    syncOptions:      
    - CreateNamespace=true
