apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loderunner.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "loderunner.name" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "loderunner.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "loderunner.name" . }}
        deploy: 23-03-27-06-04-10
        version: beta-2303-27-06
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
          livenessProbe:
            httpGet:
              path: /version
              port: http
          readinessProbe:
            httpGet:
              path: /version
              port: http
          args:
          - -l
          - "1000"
          - -r
          - -s
          - http://{{ include "ngsa-memory.fullname" . }}:8080
          - -f
          - benchmark.json
          - -p
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - emptyDir: {}
        name: tmp
