apiVersion: v1
kind: Service
metadata:
  name: {{ include "loderunner.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "loderunner.name" . }}
