apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  template:
    spec:
      containers:
      - name: prometheus
        image: acraksjxdthrti3j3qu.azurecr.io/prom/prometheus:v2.30.0
        env:
          - name: PROM_EXT_LABEL_CLUSTER
            value: aks-jxdthrti3j3qu-westus3
      - name: thanos
        image: acraksjxdthrti3j3qu.azurecr.io/thanos/thanos:v0.23.0
