export AutomationResourceGroupName=rg-trfalls-automation
export Location=eastus
export AutomationAccountName=aa-trfalls-automation
export Sku=Basic
export IdentityName=mi-trfalls-automation
export Subscription=jofultz-team
export PowerShellRunbookName=trfalls-firewall-automation
export PowerShellRunbookFileName=firewallAutomationForCostOptimization.Runbook.ps1
export PowerShellRunbookDescription="This runbook will automate the allocation and de-allocation of a firewall for cost purposes."
export PowerShellRunbookOutputFolder=.
export Asb_Environment=dev 
export BaseScheduleNameStart=wcnp-firewall-start-
export BaseScheduleNameStop=wcnp-firewall-stop-