apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
spec:
  dnsNames:
  - webhook-service.default.svc
  - webhook-service.default.svc.cluster.local
  - localhost
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-service-cert
  subject:
    organizations:
    - k8s-sig-cluster-lifecycle
