apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-{{ .Values.testlabel }}-guestbook
  labels:
    testlabel: {{ .Values.testlabel }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"

spec:
  project: default
  source:
    path: guestbook
    repoURL:  https://github.com/argoproj/argocd-example-apps/
    targetRevision:  HEAD
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
        prune: false
        selfHeal: true
    retry:
      limit: 3
    syncOptions:      
    - CreateNamespace=true 
  