apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: grafana-id
  namespace: monitoring
spec:
  type: 0
  resourceID: /subscriptions/5dc45b2f-bf13-4281-b763-a53f57290aa3/resourcegroups/rg-wcnp-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/wcnp-ngsa-id
  clientID: f6e69e97-5e96-4e7f-a17a-303554e064f1

---

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: grafana-id-binding
  namespace: monitoring
spec:
  azureIdentity: grafana-id
  selector: grafana-id

---

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  provider: azure
  secretObjects:
  - secretName: grafana-aad-client-secret
    type: Opaque
    data:
      - objectName: grafana-aad-client-secret
        key: clientSecret
  - secretName: grafana-azure-monitor-client-secret
    type: Opaque
    data:
      - objectName: grafana-azure-monitor-client-secret
        key: clientSecret
  parameters:
    usePodIdentity: "true"
    keyvaultName: "kv-aks-jxdthrti3j3qu"
    objects: |
      array:
        - |
          objectName: grafana-aad-client-secret
          objectType: secret
        - |
          objectName: grafana-azure-monitor-client-secret
          objectType: secret
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"
