apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: grafana
          image: acraks3i2qzkkxofr7c.azurecr.io/grafana/grafana:8.5.5
          env:
          - name: GF_SERVER_ROOT_URL
            value: "https://%(domain)s/"
          - name: GF_SERVER_DOMAIN
            value: "grafana-eastus-dev.cse.ms"
          - name: PROMETHEUS_QUERY_URL # For data source
            value: "http://thanos-query.monitoring.svc.cluster.local:10902"
          - name : AZURE_LA_WORKSPACE # For data source
            value: "128a9fb0-cbb6-4730-8a8b-1c540b62315c"
          - name: GF_AUTH_AZUREAD_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: grafana-aad-client-secret
                key: clientSecret
          - name: AZURE_MONITOR_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: grafana-azure-monitor-client-secret
                key: clientSecret
          volumeMounts:
            - name: grafana-secrets
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: grafana-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: grafana-secrets
      nodeSelector:
        agentpool: npuser01
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: monitoring
spec:
  hosts:
  - grafana-eastus-dev.cse.ms
