
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: ngsa-asb-loderunner-id
  namespace: loderunner
spec:
  type: 0
  resourceID: /subscriptions/648dcb5a-de1e-48b2-af6b-fe6ef28d355c/resourcegroups/rg-ngsa-asb-pre/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ngsa-asb-loderunner-id
  clientID: b1fb5e90-d919-4c8f-8f44-9f05de63cc30

---

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: ngsa-asb-loderunner-id-binding
  namespace: loderunner
spec:
  azureIdentity: ngsa-asb-loderunner-id
  selector: ngsa-asb-loderunner-id

---

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: lr-secrets
  namespace: loderunner 
spec:
  provider: azure
  secretObjects:
  - secretName: CosmosLRDatabase
    type: Opaque
    data:
    - objectName: CosmosDatabase
      key: key
  - secretName: CosmosLRCollection
    type: Opaque
    data:
    - objectName: CosmosCollection
      key: key
  - secretName: CosmosKey
    type: Opaque
    data:
    - objectName: CosmosKey
      key: key
  - secretName: CosmosUrl
    type: Opaque
    data:
    - objectName: CosmosUrl
      key: key
  parameters:
    usePodIdentity: "true"
    keyvaultName: "kv-aks-ri3aov7twb4uy"
    objects: |
      array:
        - |
          objectName: CosmosLRDatabase
          objectAlias: CosmosDatabase
          objectType: secret
        - |
          objectName: CosmosLRCollection
          objectAlias: CosmosCollection
          objectType: secret
        - |
          objectName: CosmosKey
          objectType: secret
        - |
          objectName: CosmosUrl
          objectType: secret
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
