apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/apps/monitoring/ # Then apply rest of monitoring
- grafana/04-grafana-pod-identity.yaml
patchesStrategicMerge:
- "prometheus/prometheus-patch.yaml"
- "grafana/grafana-patch.yaml"
