apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/apps/monitoring/
- grafana/04-grafana-pod-identity.yaml
patches:
- path: prometheus/prometheus-deploy-patch.yaml
- path: prometheus/prometheus-vs-patch.yaml
- path: grafana/grafana-deploy-patch.yaml
- path: grafana/grafana-vs-patch.yaml
