---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s # detect drift and undo kubectl edits every 10mins
  path: ./flux-init/init-preprod
  prune: true # remove stale resources from cluster
  targetNamespace: flux-system # set the namespace for all resources
  sourceRef:
    kind: GitRepository
    name: asb-repo-flux
    namespace: flux-system # points to namespace where this GitRepository is
  patches:
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraksfykg5bqasutle.azurecr.io/fluxcd/helm-controller:v0.22.2"        
      target:
        kind: Deployment
        name: helm-controller
        namespace: flux-system
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraksfykg5bqasutle.azurecr.io/fluxcd/kustomize-controller:v0.27.0"        
      target:
        kind: Deployment
        name: kustomize-controller
        namespace: flux-system
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraksfykg5bqasutle.azurecr.io/fluxcd/notification-controller:v0.25.1"        
      target:
        kind: Deployment
        name: notification-controller
        namespace: flux-system
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraksfykg5bqasutle.azurecr.io/fluxcd/source-controller:v0.26.1"        
      target:
        kind: Deployment
        name: source-controller
        namespace: flux-system
