apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
resources:
- ../base
patches:
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraksri3aov7twb4uy.azurecr.io/fluxcd/helm-controller:v0.33.0"        
      target:
        kind: Deployment
        name: helm-controller
        namespace: flux-system
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraksri3aov7twb4uy.azurecr.io/fluxcd/kustomize-controller:v1.0.0-rc.3"        
      target:
        kind: Deployment
        name: kustomize-controller
        namespace: flux-system
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraksri3aov7twb4uy.azurecr.io/fluxcd/notification-controller:v1.0.0-rc.3"        
      target:
        kind: Deployment
        name: notification-controller
        namespace: flux-system
    - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraksri3aov7twb4uy.azurecr.io/fluxcd/source-controller:v1.0.0-rc.3"        
      target:
        kind: Deployment
        name: source-controller
        namespace: flux-system
    - patch: |- # Remove default secret volm
        - op: replace
          path: /spec/path
          value: ./flux-init/init-preprod
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        name: flux-system
        namespace: flux-system
