---
apiVersion: v1
kind: Namespace
metadata:
  name: fluentbit
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: loderunner
  name: loderunner
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: ngsa
  name: ngsa
