apiVersion: v1
kind: Service
metadata:
  name: fluentbit-api
  namespace: fluentbit
spec:
  type: ClusterIP
  ports:
    - port: 2020
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/name: fluentbit
---
