apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-cosmos
  namespace: ngsa
  labels:
    app.kubernetes.io/name: ngsa-cosmos
spec:
  selector:
    matchLabels:
      app: ngsa-cosmos
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        aadpodidbinding: wcnp-ngsa-id
        app: ngsa-cosmos
        deploy: 23-05-21-06-04-10
        version: beta-2305-21-06
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: istio-proxy
          image: auto
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 256Mi
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-app:beta
          imagePullPolicy: Always
          args:
          - --prometheus
          - --no-cache
          - --zone
          - az-westus3-dev
          - --region
          - westus3
          - --cosmos-auth-type
          - ManagedIdentity
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /version
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 300
            httpGet:
              path: /healthz
              port: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - name: secrets
              mountPath: "/app/secrets"
            - mountPath: /tmp
              name: tmp
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ngsa-secrets
        - emptyDir: {}
          name: tmp
      nodeSelector:
        kubernetes.azure.com/mode: user

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-cosmos
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ngsa-cosmos

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ngsa-cosmos-vs
  namespace: ngsa
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - ngsa-cosmos-westus3-dev.austinrdc.dev
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: ngsa-cosmos

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ngsa-cosmos
  namespace: ngsa
  labels:
    app: ngsa-cosmos
    version: v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ngsa-cosmos
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
