apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
    - clusters: 
        selector:
          matchLabels:
            argocd.argoproj.io/secret: cluster
  template:
    metadata:
      name: 'addon-root'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/retaildevcrews/ngsa-asb
          targetRevision: anguyen/argo-helm
          path: spikes/argo-helm/multi-apps/apps
          helm:
            parameters:
            - name: 'clusterName'
              value: 'managed-cluster-1'
            valueFiles:
            - $values/spikes/argo-helm/clusters/managed-cluster-1/values.yaml
        - ref: values
          repoURL: https://github.com/retaildevcrews/ngsa-asb
          targetRevision: anguyen/argo-helm
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
        retry:
          limit: 2