apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ngsa
spec:
  generators:
  - list:
      elements:
      - cluster: argo-cluster
        url: https://kubernetes.default.svc
        env: argo
      - cluster: argo-cluster2
        url: https://argocluste-argoresource-ce2cc3-7wwuiish.hcp.southcentralus.azmk8s.io:443
        env: argo2
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
              - argo
          maxUpdate: 1
        - matchExpressions:
          - key: envLabel
            operator: In
            values:
              - argo2
          maxUpdate: 2
  goTemplate: true
  template:
    metadata:
      name: '{{.cluster}}-ngsa'
      labels:
        envLabel: '{{.env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/retaildevcrews/ngsa-asb
        targetRevision: anguyen/argo-spike
        path: spikes/argo-cd/deploy/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: ngsa
      syncPolicy:
          syncOptions:
          - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
