apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ngsa
spec:
  generators:
  - list:
      elements:
      - cluster: argo-cluster
        url: https://kubernetes.default.svc
      - cluster: argo-cluster2
        url: https://sccluster2-argoresource-ce2cc3-dytsmyjk.hcp.southcentralus.azmk8s.io:443
  strategy:
    type: RollingUpdate
    rollingUpdate:
      steps:
        - matchExpressions:
          - key: secret-type
            operator: In
            values:
              - cluster
          maxUpdate: 1
  template:
    metadata:
      name: '{{cluster}}-ngsa'
      labels:
        secret-type: "{{metadata.labels.cluster/secret-type}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/retaildevcrews/ngsa-asb
        targetRevision: anguyen/argo-spike
        path: spikes/argo-cd/deploy/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: ngsa
      syncPolicy:
          syncOptions:
          - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
