---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluentbit
  namespace: fluentbit
spec:
  # dependsOn:
  # - name: observability
  interval: 1m0s # detect drift and undo kubectl edits every minute
  prune: true # remove stale resources from cluster
  targetNamespace: fluentbit # overwrite the ns for resources in path
  path: ./deploy/pre-ngsa-asb-westus3/fluentbit
  sourceRef:
    kind: GitRepository
    name: asb-repo-flux
    namespace: flux-system # points to namespace where this GitRepository is
