apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apps/fluentbit
patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: fluentbit-log-config
        namespace: fluentbit
      data:
        zone: az-westus3-pre
        region: westus3
  - patch: |
        - op: replace
          path: "/spec/template/spec/containers/0/image"
          value: "acraksri3aov7twb4uy.azurecr.io/fluent/fluent-bit:1.9.5"        
    target:
      kind: DaemonSet
      name: fluentbit
      namespace: fluentbit
