apiVersion: apps/v1
kind: Deployment
metadata:
  name: loderunner
  namespace: loderunner
  labels:
    app.kubernetes.io/name: loderunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loderunner
  template:
    metadata:
      labels:
        app: loderunner
        deploy: 23-01-31-06-04-29
        version: beta-2301-31-06
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-lr:beta
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /version
              port: http
          readinessProbe:
            httpGet:
              path: /version
              port: http
          args:
          - -l
          - "1000"
          - -r
          - -s
          - http://ngsa-memory.ngsa:8080
          - http://ngsa-cosmos.ngsa:8080
          - http://ngsa-java.ngsa:8080
          - -f
          - benchmark.json
          - -p
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - emptyDir: {}
        name: tmp
---

apiVersion: v1
kind: Service
metadata:
  name: loderunner
  namespace: loderunner
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: loderunner
