apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - values:
                    component: prometheus
                    branch: anguyen/argo-helm
                    namespace: ngsa
                - values:
                    component: guestbook
                    branch: anguyen/argo-helm
                    namespace: ngsa
          - clusters: 
              selector:
                matchLabels:
                  argocd.argoproj.io/secret: cluster
  template:
    metadata:
      name: '{{values.component}}-{{name}}-root'
      labels:
        component: '{{values.component}}'
        cluster-id: '{{name}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/retaildevcrews/ngsa-asb
          targetRevision: '{{values.branch}}'
          path: spikes/argo-helm/single-apps/apps/{{values.component}}
          helm:
            parameters:
            - name: 'clusterName'
              value: '{{name}}'
            valueFiles:
            - $values/spikes/argo-helm/clusters/{{name}}/values.yaml
        - ref: values
          repoURL: https://github.com/retaildevcrews/ngsa-asb
          targetRevision: anguyen/argo-helm
      destination:
        name: 'in-cluster'
        namespace: 'argocd'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
        retry:
          limit: 2