---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio
  namespace: istio-system
spec:
  dependsOn:
  - name: bootstrapped-istio
    namespace: istio-operator
  interval: 1m0s # detect drift and undo kubectl edits every minute
  prune: true # remove stale resources from cluster
  targetNamespace: istio-system # overwrite the ns for resources in path
  path: ./deploy/pre-ngsa-asb-centralus/istio
  sourceRef:
    kind: GitRepository
    name: asb-repo-flux
    namespace: flux-system # points to namespace where this GitRepository is
