---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-log-config
  namespace: fluentbit
data:
  zone: az-eastus-dev
  region: eastus
  lodeLog: loderunner
  ngsaLog: ngsa
  istioLog: ingress
