cluster-name: managed-cluster-1
destination:
    server: https://kubernetes.default.svc
source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 20.1.0
configmapReload:
  prometheus:
    enabled: false