
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: $ASB_LR_MI_NAME
  namespace: loderunner
spec:
  type: 0
    resourceID: $ASB_LR_MI_RESOURCE_ID
    clientID: $ASB_LR_MI_CLIENT_ID

---

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: ${ASB_LR_MI_NAME}-binding
  namespace: loderunner
spec:
  azureIdentity: $ASB_LR_MI_NAME
  selector: $ASB_LR_MI_NAME

---

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: lr-secrets
  namespace: loderunner 
spec:
  provider: azure
  secretObjects:
  - secretName: CosmosLRDatabase
    type: Opaque
    data:
    - objectName: CosmosDatabase
      key: key
  - secretName: CosmosLRCollection
    type: Opaque
    data:
    - objectName: CosmosCollection
      key: key
  - secretName: CosmosKey
    type: Opaque
    data:
    - objectName: CosmosKey
      key: key
  - secretName: CosmosUrl
    type: Opaque
    data:
    - objectName: CosmosUrl
      key: key
  parameters:
    usePodIdentity: "true"
    keyvaultName: "$ASB_KV_NAME"
    objects: |
      array:
        - |
          objectName: CosmosLRDatabase
          objectAlias: CosmosDatabase
          objectType: secret
        - |
          objectName: CosmosLRCollection
          objectAlias: CosmosCollection
          objectType: secret
        - |
          objectName: CosmosKey
          objectType: secret
        - |
          objectName: CosmosUrl
          objectType: secret
    tenantId: "$ASB_TENANT_ID"
