kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: workload-cluster-3
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
    extraPortMappings:
      - containerPort: 30083
        hostPort: 30083
