apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ngsa-memory.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ngsa-memory.name" . }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "ngsa-memory.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ngsa-memory.name" . }}
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          imagePullPolicy: Always
          args: 
          - --in-memory
          - --prometheus
          - --zone
          - {{ .Values.zone }}
          - --region
          - {{ .Values.region }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /version
              port: {{ .Values.port }}
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 300
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - emptyDir: {}
          name: tmp
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        kubernetes.azure.com/mode: user
