apiVersion: v1
kind: Service
metadata:
  name: {{ include "ngsa-memory.fullname" . }}
  namespace: {{ .Release.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "ngsa-memory.name" . }}
