{
 "title": "NGSA - Azure Monitor Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Zone",
    "query": "East US: eastus, West US3: westus3, North Central US: northcentralus"
   }
  ]
 },
 "panels": [
  { "title": "Cosmos DB Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throttled Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "AzureDiagnostics\n| where ResourceProvider==\"MICROSOFT.DOCUMENTDB\" and Category == \"DataPlaneRequests\" and Resource == \"WCNP-PRE-COSMOS\"\n| where databaseName_s == \"imdb\"\n| where statusCode_s == 429\n| count",
      "resultFormat": "time_series",
      "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
    }
   ]
  },
  {
   "title": "Total Requests (ngsa-pre-cosmos)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7f7b8792-0860-4fbf-83a1-32018810805e"
     },
     "azureMonitor": {
      "aggOptions": [ "Count" ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "StatusCode", "value": "StatusCode" },
       { "text": "OperationType", "value": "OperationType" },
       { "text": "Status", "value": "Status" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "rg-wcnp-pre-cosmos",
      "resourceName": "wcnp-pre-cosmos",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7f7b8792-0860-4fbf-83a1-32018810805e"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "StatusCode", "value": "StatusCode" },
       { "text": "OperationType", "value": "OperationType" },
       { "text": "Status", "value": "Status" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "TotalRequestUnits",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "rg-wcnp-pre-cosmos",
      "resourceName": "wcnp-pre-cosmos",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
    }
   ]
  },
  {
   "title": "Max Provisioned Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "AzureMetrics \n| where MetricName == \"ProvisionedThroughput\" and Resource == \"WCNP-PRE-COSMOS\"\n| summarize max(Count) ",
      "resultFormat": "time_series",
      "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "ngsa-pre-shared-rg",
      "resourceName": "select",
      "timeGrain": "",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "          Server Response Time Percentile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Response Time (ngsa-cosmos)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) \n   and k_container_s == 'app'\r\n   and k_app_s == 'ngsa-cosmos'\r\n   and LogName_s == \"Ngsa.RequestLog\" \n   and Zone_s has_any ($Zone)\n   and UserAgent_s startswith \"l8r/\"\n\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, k_app_s\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType=k_app_s\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "Server Response Time (ngsa-memory)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) \n   and k_container_s == 'app'\r\n   and k_app_s == 'ngsa-memory'\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\n   and UserAgent_s startswith \"l8r/\"\n\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, k_app_s\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType=k_app_s\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "Server Response Time (ngsa-java)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 10 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) \n   and k_container_s == 'app'\r\n   and k_app_s == 'ngsa-java'\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\n   and UserAgent_s startswith \"l8r/\"\n\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, k_app_s\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType=k_app_s\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Server Response Time (ngsa-cosmos)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 18 },
     "repeat": "Zone",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n   and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-cosmos'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and UserAgent_s startswith \"l8r/\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Server Response Time (ngsa-memory)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 18 },
     "repeat": "Zone",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n    and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-memory'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and UserAgent_s startswith \"l8r/\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Server Response Time (ngsa-java)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 18 },
     "repeat": "Zone",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n    and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-java'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and UserAgent_s startswith \"l8r/\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Server Response Time (ngsa-cosmos)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n   and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-cosmos'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and UserAgent_s startswith \"l8r/\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Server Response Time (ngsa-memory)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n    and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-memory'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and UserAgent_s startswith \"l8r/\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Server Response Time (ngsa-java)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n    and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-java'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and UserAgent_s startswith \"l8r/\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Server Response Time (ngsa-cosmos)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n   and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-cosmos'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and UserAgent_s startswith \"l8r/\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Server Response Time (ngsa-memory)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n    and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-memory'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and UserAgent_s startswith \"l8r/\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Server Response Time (ngsa-java)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n    and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-java'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and UserAgent_s startswith \"l8r/\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    }
   ]
  },
  {
   "title": "          Client Response Time Percentile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Response Time (ngsa-cosmos)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 115 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-cosmos'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, AppType\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "Client Response Time (ngsa-memory)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 115 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-memory'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, AppType\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "Client Response Time (ngsa-java)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 115 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-java'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, AppType\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time (ngsa-cosmos)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 123 },
     "repeat": "Zone",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time (ngsa-memory)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 123 },
     "repeat": "Zone",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time (ngsa-java)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 123 },
     "repeat": "Zone",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time (ngsa-cosmos)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 131 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time (ngsa-memory)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 131 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time (ngsa-java)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 131 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time (ngsa-cosmos)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 139 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time (ngsa-memory)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 139 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time (ngsa-java)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 139 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    }
   ]
  },
  {
   "title": "          Client Response Time by category",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Zone Client Response Time by Category (ngsa-cosmos)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 148 },
     "repeat": "Zone",
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-cosmos'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time by Category (ngsa-memory)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 148 },
     "repeat": "Zone",
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-memory'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time by Category (ngsa-java)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 148 },
     "repeat": "Zone",
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-java'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time by Category (ngsa-cosmos)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 156 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-cosmos'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time by Category (ngsa-memory)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 156 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-memory'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time by Category (ngsa-java)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 156 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-java'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time by Category (ngsa-cosmos)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 164 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-cosmos'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time by Category (ngsa-memory)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 164 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-memory'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    },
    {
     "title": "$Zone Client Response Time by Category (ngsa-java)",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 164 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone) and (k_app_s == \"loderunner\" or k_app_s == \"loderunner-clientmode\")\r\n| extend AppType = 'ngsa-java'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
        "resultFormat": "time_series",
        "workspace": "35e52811-9906-4cb9-9b75-b4f313f22010"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "select",
        "metricName": "select",
        "metricNamespace": "select",
        "resourceGroup": "select",
        "resourceName": "select",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "5dc45b2f-bf13-4281-b763-a53f57290aa3"
      }
     ]
    }
   ]
  }
 ]
}