{
 "title": "NGSA Pre - Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "region", "query": "eastus" },
   {
    "name": "service",
    "query": "ngsa-cosmos,ngsa-memory,ngsa-java"
   },
   {
    "name": "mode",
    "query": "read:Direct|Query,write:Upsert|Delete"
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_bucket{region=~\"$region\",job=~\"$service.*\",mode=~\"$mode\"}[1m])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Avg RPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_count{region=~\"$region\",job=~\"$service.*\",mode=~\"$mode\"}[1m]))"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Server Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(NgsaAppSummary{code=\"OK\",job=~\"$service.*\",region=~\"$region\",mode=~\"$mode\",quantile=~\"0.95|0.99\"}) by (mode, quantile)",
     "legendFormat": "P {{quantile}} {{mode}}"
    }
   ]
  },
  {
   "title": "LodeRunner Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(LodeRunnerSummary{code=\"OK\",server=~\".*$service.*\",mode=~\"$mode\",quantile=~\"0.95|0.99\"}) by (mode, quantile)",
     "legendFormat": "P {{quantile}} {{mode}}"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_count{region=~\"$region\",service=~\"$service.*\",code=~\"Warn|Error\",mode=~\"$mode\"}[1m]))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Retry Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(NgsaAppDuration_count{region=~\"$region\",service=~\"$service.*\",code = \"Retry\"}[1m]))",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}