{
 "title": "NGSA Pre - Azure Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Zone", "query": "az-eastus-pre" }
  ]
 },
 "panels": [
  { "title": "Cosmos DB Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throttled Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "AzureDiagnostics\n| where ResourceProvider==\"MICROSOFT.DOCUMENTDB\" and Category == \"DataPlaneRequests\" and Resource == \"NGSA-ASB-PRE-COSMOS2\"\n| where databaseName_s == \"imdb\"\n| where statusCode_s == 429\n| count",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Total Requests (ngsa-pre-cosmos)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7f7b8792-0860-4fbf-83a1-32018810805e"
     },
     "azureMonitor": {
      "aggOptions": [ "Count" ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "StatusCode", "value": "StatusCode" },
       { "text": "OperationType", "value": "OperationType" },
       { "text": "Status", "value": "Status" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "rg-ngsa-asb-pre-cosmos",
      "resourceName": "ngsa-asb-pre-cosmos2",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7f7b8792-0860-4fbf-83a1-32018810805e"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "StatusCode", "value": "StatusCode" },
       { "text": "OperationType", "value": "OperationType" },
       { "text": "Status", "value": "Status" }
      ],
      "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
      "metricName": "TotalRequestUnits",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "resourceGroup": "rg-ngsa-asb-pre-cosmos",
      "resourceName": "ngsa-asb-pre-cosmos2",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Max Provisioned Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "AzureMetrics \n| where MetricName == \"ProvisionedThroughput\" and Resource == \"NGSA-ASB-PRE-COSMOS2\"\n| summarize max(Count) ",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "ngsa-pre-shared-rg",
      "resourceName": "select",
      "timeGrain": "",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "          Successful Server Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "ngsa-cosmos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where  k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-cosmos\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n\r\n| summarize RequestSuccessRate = round(100.0*countif(StatusCode_d < 400)/count(),4)\r\n| project RequestSuccessRate",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "ngsa-memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where  k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-memory\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n\r\n| summarize RequestSuccessRate = round(100.0*countif(StatusCode_d < 400)/count(),4)\r\n| project RequestSuccessRate",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "ngsa-java",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where  k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-java\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n\r\n| summarize RequestSuccessRate = round(100.0*countif(StatusCode_d < 400)/count(),4)\r\n| project RequestSuccessRate",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "% Successful Server Requests (ngsa-cosmos)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where  $__timeFilter(Date_t)\n   and k_container_s == \"app\"\r\n   and k_app_s == \"ngsa-cosmos\" \r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n| summarize RequestSuccessRate = 100.0 * countif(StatusCode_d < 400) / count() by bin_at(Date_t, 2m, datetime(00:00))\r\n| project-rename Date=Date_t",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "% Successful Server Requests (ngsa-memory)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where  $__timeFilter(Date_t) \n   and k_container_s == \"app\"\r\n   and k_app_s == \"ngsa-memory\" \r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n| summarize RequestSuccessRate = 100.0 * countif(StatusCode_d < 400) / count() by bin_at(Date_t, 2m, datetime(00:00))\r\n| project-rename Date=Date_t",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "% Successful Server Requests (ngsa-java)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where  $__timeFilter(Date_t) \n   and k_container_s == \"app\"\r\n   and k_app_s == \"ngsa-java\" \r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n| summarize RequestSuccessRate = 100.0 * countif(StatusCode_d < 400) / count() by bin_at(Date_t, 2m, datetime(00:00))\r\n| project-rename Date=Date_t",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "          Failed Server Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "ngsa-cosmos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t)\n   and k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-cosmos\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n\r\n| summarize FailedRequestCount=countif(StatusCode_d >= 400)\r\n| project FailedRequestCount",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "ngsa-memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t)\n   and k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-memory\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n\r\n| summarize FailedRequestCount=countif(StatusCode_d >= 400)\r\n| project FailedRequestCount",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "ngsa-java",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t)\n   and k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-java\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n\r\n| summarize FailedRequestCount=countif(StatusCode_d >= 400)\r\n| project FailedRequestCount",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Failed Server Requests (ngsa-cosmos)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let _series_data = materialize(\r\nngsa_CL\r\n| where $__timeFilter(Date_t)\r\n   and  k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-cosmos\"  \r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)   \r\n| summarize FailedRequests=countif(StatusCode_d >= 400) by StatusCode_d , bin(Date_t, 1m) );\r\n\r\n\r\n\r\n_series_data \r\n| summarize sum(FailedRequests) by Date_t\n| project-rename FailedRequests=sum_FailedRequests\n\r\n| order by Date_t asc\n\n\r\n\n",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Failed Server Requests (ngsa-memory)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let _series_data = materialize(\r\nngsa_CL\r\n| where $__timeFilter(Date_t)\r\n   and  k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-memory\"  \r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n| summarize FailedRequests=countif(StatusCode_d >= 400) by StatusCode_d , bin(Date_t, 1m) );\r\n\r\n\r\n\r\n_series_data \r\n| summarize sum(FailedRequests) by Date_t\n| project-rename FailedRequests=sum_FailedRequests\r\n| order by Date_t asc\n\n\r\n\n",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Failed Server Requests (ngsa-java)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let _series_data = materialize(\r\nngsa_CL\r\n| where $__timeFilter(Date_t)\r\n   and  k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-java\"  \r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n| summarize FailedRequests=countif(StatusCode_d >= 400) by StatusCode_d , bin(Date_t, 1m) );\r\n\r\n\r\n\r\n_series_data \r\n| summarize sum(FailedRequests) by Date_t\n| project-rename FailedRequests=sum_FailedRequests\r\n| order by Date_t asc\n\n\r\n\n",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "          Average LodeRunner Requests Per Minute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "ngsa-cosmos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t)\n  and k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-cosmos\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n\r\n| summarize count() by bin(Date_t,1m)\r\n| summarize round(avg(count_),0)\r\n| project AvgRequests=avg_count_",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "ngsa-memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t)\n  and k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-memory\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n\r\n| summarize count() by bin(Date_t,1m)\r\n| summarize round(avg(count_),0)\r\n| project AvgRequests=avg_count_",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "ngsa-java",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t)\n  and k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-java\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)\r\n\r\n| summarize count() by bin(Date_t,1m)\r\n| summarize round(avg(count_),0)\r\n| project AvgRequests=avg_count_",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  { "title": "          Server Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Server Requests (ngsa-cosmos)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t)\n   and k_container_s == \"app\"\r\n   and k_app_s == \"ngsa-cosmos\"\n   and LogName_s == \"Ngsa.RequestLog\"\n   and Zone_s has_any ($Zone)   \r\n| summarize count() by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t,ServerRequests=count_\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Server Requests (ngsa-memory)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where  $__timeFilter(Date_t)\n   and  k_container_s == \"app\"\r\n   and k_app_s == \"ngsa-memory\" \r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n    and Zone_s has_any ($Zone)  \r\n| summarize count() by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ServerRequests=count_\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Server Requests (ngsa-java)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where  $__timeFilter(Date_t)\n   and  k_container_s == \"app\"\r\n   and k_app_s == \"ngsa-java\" \r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\n    and Zone_s has_any ($Zone)  \r\n| summarize count() by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ServerRequests=count_\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "          Failed Server Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Failed Requests (ngsa-cosmos)",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 43 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) \n    and k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-cosmos\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\r\n\r\n   and StatusCode_d >= 400\n   and Zone_s has_any ($Zone)\r\n| summarize count() by tostring(toint(StatusCode_d)), Path_s, Zone_s\r\n| project-rename StatusCode=StatusCode_d,RequestCount=count_,Path=Path_s, Zone=Zone_s",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Failed Requests (ngsa-memory)",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 43 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) \n    and k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-memory\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\r\n\r\n   and StatusCode_d >= 400\n    and Zone_s has_any ($Zone)  \r\n| summarize count() by tostring(toint(StatusCode_d)), Path_s, Zone_s\r\n| project-rename StatusCode=StatusCode_d,RequestCount=count_,Path=Path_s, Zone=Zone_s",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Failed Requests (ngsa-java)",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 43 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) \n    and k_container_s == \"app\" \r\n   and k_app_s == \"ngsa-java\" \r\n   and LogName_s == \"Ngsa.RequestLog\"\r\n\r\n   and StatusCode_d >= 400\n    and Zone_s has_any ($Zone)  \r\n| summarize count() by tostring(toint(StatusCode_d)), Path_s, Zone_s\r\n| project-rename StatusCode=StatusCode_d,RequestCount=count_,Path=Path_s, Zone=Zone_s",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "          Failed Client Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }
  },
  {
   "title": "LodeRunner Failures (Client)",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 51 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where $__timeFilter(Date_t) and StatusCode_d > 200 and Zone_s has_any ($Zone)\r\n| extend AppType = case(Server_s contains 'ngsa-memory', \"ngsa-memory\", \r\n                      Server_s contains 'ngsa-cosmos', \"ngsa-cosmos\", \r\n                      Server_s contains 'ngsa-java', \"ngsa-java\", \r\n                       \"unknown!\")\r\n| summarize countif(StatusCode_d > 200) by AppType, Zone_s, StatusCode_d\r\n| project-rename FailureCount=countif_, Zone=Zone_s, StatusCode=StatusCode_d\r\n| order by AppType, Zone, StatusCode",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "          Server Response Time Percentile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "Server Response Time (ngsa-cosmos)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 61 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) \n   and k_container_s == 'app'\r\n   and k_app_s == 'ngsa-cosmos'\r\n   and LogName_s == \"Ngsa.RequestLog\" \n   and Zone_s has_any ($Zone)\n\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, k_app_s\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType=k_app_s\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Server Response Time (ngsa-memory)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 61 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) \n   and k_container_s == 'app'\r\n   and k_app_s == 'ngsa-memory'\r\n   and LogName_s == \"Ngsa.RequestLog\"\n      and Zone_s has_any ($Zone)\n\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, k_app_s\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType=k_app_s\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Server Response Time (ngsa-java)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 61 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) \n   and k_container_s == 'app'\r\n   and k_app_s == 'ngsa-java'\r\n   and LogName_s == \"Ngsa.RequestLog\"\n      and Zone_s has_any ($Zone)\n\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, k_app_s\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType=k_app_s\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Server Response Time (ngsa-cosmos)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n    and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-cosmos'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Server Response Time (ngsa-memory)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n    and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-memory'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Server Response Time (ngsa-java)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ngsa_CL\r\n| where $__timeFilter(Date_t) and Zone_s has_any ($Zone)\n    and k_container_s == \"app\"\r\n   and k_app_s == 'ngsa-java'\r\n\r\n   and LogName_s == \"Ngsa.RequestLog\"\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90,  ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "          Client Response Time Percentile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 }
  },
  {
   "title": "Client Response Time (ngsa-cosmos)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 78 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| extend AppType = 'ngsa-cosmos'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, AppType\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Client Response Time (ngsa-memory)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 78 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| extend AppType = 'ngsa-memory'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, AppType\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Client Response Time (ngsa-java)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 78 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| extend AppType = 'ngsa-java'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Zone_s, AppType\r\n| extend Zone=Zone_s, 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2), AppType\r\n| project AppType, Zone, 75th, 90th, 95th, 98th\r\n| order by AppType, Zone asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Client Response Time (ngsa-cosmos)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Client Response Time (ngsa-memory)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Client Response Time (ngsa-java)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by bin_at(Date_t, 1m, datetime(00:00))\r\n| project-rename Date=Date_t, ResponseTime_75th=percentile_Duration_d_75, ResponseTime_90th=percentile_Duration_d_90, ResponseTime_95th=percentile_Duration_d_95, ResponseTime_98th=percentile_Duration_d_98\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "          Client Response Time by category",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 }
  },
  {
   "title": "Client Response Time by Category (ngsa-cosmos)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 95 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| extend AppType = 'ngsa-cosmos'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Client Response Time by Category (ngsa-memory)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 95 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| extend AppType = 'ngsa-memory'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Client Response Time by Category (ngsa-java)",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 95 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| extend AppType = 'ngsa-java'\r\n| summarize percentile(Duration_d, 75), percentile(Duration_d, 90), percentile(Duration_d, 95), percentile(Duration_d, 98) by Category, AppType\r\n| extend 75th=round(percentile_Duration_d_75,2), 90th=round(percentile_Duration_d_90,2), 95th=round(percentile_Duration_d_95,2), 98th=round(percentile_Duration_d_98,2)\r\n| project AppType, Category, 75th, 90th, 95th, 98th\r\n| order by AppType, Category asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Client Response Time by Category (ngsa-cosmos)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-cosmos' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| sample 7000\r\n| project-rename ResponseTime=Duration_d, Date=Date_t\r\n| project ResponseTime, Category, Date\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Client Response Time by Category (ngsa-memory)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-memory' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| sample 7000\r\n| project-rename ResponseTime=Duration_d, Date=Date_t\r\n| project ResponseTime, Category, Date\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  },
  {
   "title": "Client Response Time by Category (ngsa-java)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "loderunner_CL\r\n| where Server_s contains 'ngsa-java' and $__timeFilter(Date_t) and Zone_s has_any($Zone)\r\n| sample 7000\r\n| project-rename ResponseTime=Duration_d, Date=Date_t\r\n| project ResponseTime, Category, Date\r\n| order by Date asc",
      "resultFormat": "time_series",
      "workspace": "b51964b6-4a46-46f2-80b9-01f0649e63f5"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "648dcb5a-de1e-48b2-af6b-fe6ef28d355c"
    }
   ]
  }
 ]
}