---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-log-config
  namespace: fluentbit
data:
  zone: az-centralus-pre
  region: centralus
  lodeLog: loderunner
  ngsaLog: ngsa
  istioLog: ingress
