apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  template:
    spec:
      volumes:
      - name: prometheus-config-shared
        emptyDir: {}
      - name: thanos-objstore-config
        secret:
          secretName: thanos-objstore-config
      containers:
      - name: prometheus
        image: acraks3i2qzkkxofr7c.azurecr.io/prom/prometheus:v2.30.0
        args:
        # Base args
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus/"
        - "--storage.tsdb.retention.size=3900MB"
        - "--storage.tsdb.retention.time=7d"
        - "--enable-feature=expand-external-labels" # for env substitution of external lables in cm
        # Below args added for thanos
        - "--storage.tsdb.min-block-duration=2h"
        - "--storage.tsdb.max-block-duration=2h"
        - "--web.enable-lifecycle"
        - "--web.enable-admin-api"
        env:
          - name: PROM_EXT_LABEL_CLUSTER
            value: aks-3i2qzkkxofr7c-eastus
      - name: thanos
        image: acraks3i2qzkkxofr7c.azurecr.io/thanos/thanos:v0.23.0
        imagePullPolicy: Always
        args:
          - "sidecar"
          - "--log.level=debug"
          - "--tsdb.path=/prometheus/"
          - "--prometheus.url=http://localhost:9090"
          - "--objstore.config-file=/etc/secret/thanos-storage-config.yaml"
          - "--reloader.config-file=/etc/prometheus/prometheus.yml"
        env:
          - name : THANOS_OBJSTORE_CONFIG
            value: /etc/secret/thanos-storage-config.yaml
        ports:
          - name: http-sidecar
            containerPort: 10902
          - name: grpc
            containerPort: 10901
        resources:
          requests:
            cpu: '100m'
            memory: '64Mi'
          limits:
            cpu: '250m'
            memory: '256Mi'
        livenessProbe:
            httpGet:
              port: 10902
              path: /-/healthy
        readinessProbe:
          httpGet:
            port: 10902
            path: /-/ready
        volumeMounts:
          - name: prometheus-storage-volume
            mountPath: /prometheus
          - name: prometheus-config-volume
            mountPath: /etc/prometheus
          - name: thanos-objstore-config
            mountPath: /etc/secret
            readOnly: false
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
    - name: http-sidecar
      port: 10902
      targetPort: 10902
