apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  template:
    spec:
      containers:
      - name: prometheus
        image: acraks3i2qzkkxofr7c.azurecr.io/prom/prometheus:v2.30.0
        env:
          - name: PROM_EXT_LABEL_CLUSTER
            value: aks-3i2qzkkxofr7c-eastus
