nodeSelector: {}
tolerations: []
manager:
  # extraEnv:
  #   - name: SKIP_INIT_CONTAINER
  #     value: "true"

  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 350Mi

  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /healthz
      port: 8081
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3
    initialDelaySeconds: 10

  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /readyz
      port: 8081
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3
    initialDelaySeconds: 10

  # Set this to false to disable the experimental parallel recovery in case you are experiencing problems
  parallelRecoveryEnabled: true

  image:
    repository: "acraksjxdthrti3j3qu.azurecr.io/opsterio/opensearch-operator"
    tag: "v2.2.1"
    pullPolicy: "Always"

  dnsBase: cluster.local

  # If a watchNamespace is specified, the manager's cache will be restricted to
  # watch objects in the desired namespace. Defaults is to watch all namespaces.
  watchNamespace:

kubeRbacProxy:
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 25m
      memory: 25Mi

  livenessProbe:
    failureThreshold: 3
    tcpSocket:
      port: 8443
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3
    initialDelaySeconds: 10

  readinessProbe:
    failureThreshold: 3
    tcpSocket:
      port: 8443
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3
    initialDelaySeconds: 10

  image: 
    repository: "acraksjxdthrti3j3qu.azurecr.io/kubebuilder/kube-rbac-proxy"
    tag: "v0.8.0"