apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-guestbook
  labels:
    testlabel: 'testlabel'
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: {{.Values.source.path}}
    repoURL: {{.Values.source.repoURL}}
    targetRevision: {{.Values.source.targetRevision}}
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
