apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-{{ .Values.testlabel }}-guestbook
  labels:
    testlabel: {{ .Values.testlabel }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '{{ .Values.syncwave }}'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: {{.Values.source.path}}
    repoURL: {{.Values.source.repoURL}}
    targetRevision: {{.Values.source.targetRevision}}
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
        prune: false
        selfHeal: true
    retry:
      limit: 3
    syncOptions:      
    - CreateNamespace=true
