apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: grafana
          image: acraksfykg5bqasutle.azurecr.io/grafana/grafana:8.5.5
          env:
          - name: GF_SERVER_ROOT_URL
            value: "https://%(domain)s/"
          - name: GF_SERVER_DOMAIN
            value: "grafana-centralus-pre.cse.ms"
          - name: PROMETHEUS_QUERY_URL # For data source
            value: "http://prometheus-server.monitoring.svc:9090"
          - name : AZURE_LA_WORKSPACE # For data source
            value: "b51964b6-4a46-46f2-80b9-01f0649e63f5"
          - name: GF_AUTH_AZUREAD_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: grafana-aad-client-secret
                key: clientSecret
          - name: AZURE_MONITOR_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: grafana-azure-monitor-client-secret
                key: clientSecret
          volumeMounts:
            - name: grafana-secrets
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: grafana-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: grafana-secrets
      nodeSelector:
        agentpool: npuser01
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: monitoring
spec:
  hosts:
  - grafana-centralus-pre.cse.ms
