apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-deployment-clusterrole
rules:
- apiGroups: [""]
  resources: ["services", "pods", "deployments", "replicasets", "configmaps", "secrets", "persistentvolumeclaims", "namespaces"]
  verbs: ["*"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["*"]
