apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-deployment-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: helm-deployment-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: helm-deployment-clusterrole
  apiGroup: rbac.authorization.k8s.io
